/**
 * Copyright 2013 Facebook, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @providesModule getNodeNameFromReactMarkup
 */

"use strict";

/**
 * Extracts the `nodeName` from a string of markup generated by React.
 *
 * NOTE: Extracting the `nodeName` does not require a regular expression match
 * because we make assumptions about React-generated markup (i.e. there are no
 * spaces surrounding the opening tag and there is at least one attribute).
 *
 * @param {string} markup String of markup.
 * @return {string} Node name of the supplied markup.
 * @see http://jsperf.com/extract-nodename/2
 */
function getNodeNameFromReactMarkup(markup) {
  if (markup.charAt(0) === '<') {
    return markup.substring(1, markup.indexOf(' '));
  } else if (markup) {
    return '#text';
  } else {
    return '';
  }
}

module.exports = getNodeNameFromReactMarkup;
