# Configuration for probot-stale - https://github.com/probot/stale
# Number of days of inactivity before an issue becomes stale
daysUntilStale: 90
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - "Partner"
  - "React Core Team"
  - "Resolution: Backlog"
  - "Type: Bug"
  - "Type: Discussion"
  - "Type: Needs Investigation"
  - "Type: Regression"
# Label to use when marking an issue as stale
staleLabel: "Resolution: Stale"
issues:
  # Comment to post when marking an issue as stale.
  markComment: >
    This issue has been automatically marked as stale.
    **If this issue is still affecting you, please leave any comment** (for example, "bump"), and we'll keep it open.
    We are sorry that we haven't been able to prioritize it yet. If you have any new additional information, please include it with your comment!
  # Comment to post when closing a stale issue.
  closeComment: >
    Closing this issue after a prolonged period of inactivity. If this issue is still present in the latest release, please create a new issue with up-to-date information. Thank you!
pulls:
  # Comment to post when marking a pull request as stale.
  markComment: >
    This pull request has been automatically marked as stale.
    **If this pull request is still relevant, please leave any comment** (for example, "bump"), and we'll keep it open.
    We are sorry that we haven't been able to prioritize reviewing it yet. Your contribution is very much appreciated.
  # Comment to post when closing a stale pull request.
  closeComment: >
    Closing this pull request after a prolonged period of inactivity. If this issue is still present in the latest release, please ask for this pull request to be reopened. Thank you!
