// This is a generated file. The source files are in react-dom-bindings/src/server/fizz-instruction-set.
// The build script is at scripts/rollup/generate-inline-fizz-runtime.js.
// Run `yarn generate-inline-fizz-runtime` to generate.
export const markShellTime =
  'requestAnimationFrame(function(){$RT=performance.now()});';
export const clientRenderBoundary =
  '$RX=function(b,c,d,e,f){var a=document.getElementById(b);a&&(b=a.previousSibling,b.data="$!",a=a.dataset,c&&(a.dgst=c),d&&(a.msg=d),e&&(a.stck=e),f&&(a.cstck=f),b._reactRetry&&b._reactRetry())};';
export const completeBoundary =
  '$RB=[];$RV=function(c){$RT=performance.now();for(var a=0;a<c.length;a+=2){var b=c[a],h=c[a+1],e=b.parentNode;if(e){var f=b.previousSibling,g=0;do{if(b&&8===b.nodeType){var d=b.data;if("/$"===d||"/&"===d)if(0===g)break;else g--;else"$"!==d&&"$?"!==d&&"$~"!==d&&"$!"!==d&&"&"!==d||g++}d=b.nextSibling;e.removeChild(b);b=d}while(b);for(;h.firstChild;)e.insertBefore(h.firstChild,b);f.data="$";f._reactRetry&&f._reactRetry()}}c.length=0};$RC=function(c,a){if(a=document.getElementById(a))if(a.parentNode.removeChild(a),c=document.getElementById(c))c.previousSibling.data="$~",$RB.push(c,a),2===$RB.length&&setTimeout($RV.bind(null,$RB),("number"!==typeof $RT?0:$RT)+300-performance.now())};';
export const completeBoundaryUpgradeToViewTransitions =
  '$RV=function(w,f){function k(b,d){var g=b.getAttribute(d);g&&"none"!==g&&(d=b.style,m.push(b,d.viewTransitionName,d.viewTransitionClass),"auto"!==g&&(d.viewTransitionClass=g),(b=b.getAttribute("vt-name"))||(b="\\u00abT"+E++ +"\\u00bb"),d.viewTransitionName=b,x=!0)}var x=!1,E=0,m=[];try{var e=document.__reactViewTransition;if(e){e.finished.finally($RV.bind(null,f));return}var l=new Map;for(e=1;e<f.length;e+=2)for(var h=f[e].querySelectorAll("[vt-share]"),c=0;c<h.length;c++){var a=h[c];l.set(a.getAttribute("vt-name"),a)}for(h=0;h<f.length;h+=2){var y=f[h],t=y.parentNode;if(t){var q=t.getBoundingClientRect();if(q.left||q.top||q.width||q.height){a=t;do for(var r=a.firstElementChild;r;)k(r,"vt-update"),r=r.nextElementSibling;while((a=a.parentNode)&&1===a.nodeType&&"none"!==a.getAttribute("vt-update"));a=y;for(e=0;a;){if(8===a.nodeType){var n=a.data;if("/$"===n)if(0===e)break;else e--;else"$"!==n&&"$?"!==n&&"$~"!==n&&"$!"!==n||e++}else if(1===a.nodeType){c=a;var z=c.getAttribute("vt-name"),\nu=l.get(z);k(c,u?"vt-share":"vt-exit");u&&(k(u,"vt-share"),l.set(z,null));var A=c.querySelectorAll("[vt-share]");for(c=0;c<A.length;c++){var B=A[c],C=B.getAttribute("vt-name"),D=l.get(C);D&&(k(B,"vt-share"),k(D,"vt-share"),l.set(C,null))}}a=a.nextSibling}for(var p=f[h+1].firstElementChild;p;)null!==l.get(p.getAttribute("vt-name"))&&k(p,"vt-enter"),p=p.nextElementSibling}}}if(x){var v=document.__reactViewTransition=document.startViewTransition({update:w.bind(null,f),types:[]});v.ready.finally(function(){for(var b=\nm.length-3;0<=b;b-=3){var d=m[b],g=d.style;g.viewTransitionName=m[b+1];g.viewTransitionClass=m[b+1];""===d.getAttribute("style")&&d.removeAttribute("style")}});v.finished.finally(function(){document.__reactViewTransition===v&&(document.__reactViewTransition=null)});$RB=[];return}}catch(b){}w(f)}.bind(null,$RV);';
export const completeBoundaryWithStyles =
  '$RM=new Map;$RR=function(n,w,p){function u(q){this._p=null;q()}for(var r=new Map,t=document,h,b,e=t.querySelectorAll("link[data-precedence],style[data-precedence]"),v=[],k=0;b=e[k++];)"not all"===b.getAttribute("media")?v.push(b):("LINK"===b.tagName&&$RM.set(b.getAttribute("href"),b),r.set(b.dataset.precedence,h=b));e=0;b=[];var l,a;for(k=!0;;){if(k){var f=p[e++];if(!f){k=!1;e=0;continue}var c=!1,m=0;var d=f[m++];if(a=$RM.get(d)){var g=a._p;c=!0}else{a=t.createElement("link");a.href=d;a.rel=\n"stylesheet";for(a.dataset.precedence=l=f[m++];g=f[m++];)a.setAttribute(g,f[m++]);g=a._p=new Promise(function(q,x){a.onload=u.bind(a,q);a.onerror=u.bind(a,x)});$RM.set(d,a)}d=a.getAttribute("media");!g||d&&!matchMedia(d).matches||b.push(g);if(c)continue}else{a=v[e++];if(!a)break;l=a.getAttribute("data-precedence");a.removeAttribute("media")}c=r.get(l)||h;c===h&&(h=a);r.set(l,a);c?c.parentNode.insertBefore(a,c.nextSibling):(c=t.head,c.insertBefore(a,c.firstChild))}if(p=document.getElementById(n))p.previousSibling.data=\n"$~";Promise.all(b).then($RC.bind(null,n,w),$RX.bind(null,n,"CSS failed to load"))};';
export const completeSegment =
  '$RS=function(a,b){a=document.getElementById(a);b=document.getElementById(b);for(a.parentNode.removeChild(a);a.firstChild;)b.parentNode.insertBefore(a.firstChild,b);b.parentNode.removeChild(b)};';
export const formReplaying =
  'addEventListener("submit",function(a){if(!a.defaultPrevented){var c=a.target,d=a.submitter,e=c.action,b=d;if(d){var f=d.getAttribute("formAction");null!=f&&(e=f,b=null)}"javascript:throw new Error(\'React form unexpectedly submitted.\')"===e&&(a.preventDefault(),b?(a=document.createElement("input"),a.name=b.name,a.value=b.value,b.parentNode.insertBefore(a,b),b=new FormData(c),a.parentNode.removeChild(a)):b=new FormData(c),a=c.ownerDocument||c,(a.$$reactFormReplay=a.$$reactFormReplay||[]).push(c,d,b))}});';
