-#!/bin/bash		
 -		
 -set -e		
 -		
 -npm run build -- --extractErrors
 -git checkout -- scripts/error-codes/codes.json		
 -		
 -WARNINGS=$(node scripts/error-codes/print-warnings.js)		
 -echo "$WARNINGS"		
 -test ! -z "$WARNINGS"