const onlyFilter = new Set([
  "alias-nested-member-path",
  // // TODO: fix invalid .set call
  // // "assignment-variations-complex-lvalue-array",
  "assignment-variations-complex-lvalue",
  "assignment-variations",
  "chained-assignment-expressions",
  "computed-call-evaluation-order",
  "const-propagation-into-function-expression-primitive",
  "constant-propagation-for",
  "constant-propagation-while",
  "constant-propagation",
  "do-while-continue",
  "do-while-simple",
  "expression-with-assignment",
  "for-of-break",
  "for-of-conditional-break",
  "for-of-continue",
  "for-of-destructure",
  "for-of-simple",
  "function-declaration-reassign",
  "function-declaration-redeclare",
  "lambda-reassign-primitive",
  "lambda-reassign-shadowed-primitive",
  "property-call-evaluation-order",
  "reactive-scope-grouping",
  "sequentially-constant-progagatable-if-test-conditions",
  "simple-function-1",
  // TODO: uses jsx (requires React)
  // "sketchy-code-rules-of-hooks",
  "ssa-complex-multiple-if",
  "ssa-complex-single-if",
  // TODO: fix infinite loop
  // "ssa-for-trivial-update",
  "ssa-for",
  "ssa-if-else",
  "ssa-objectexpression-phi",
  "ssa-property-call",
  "ssa-property",
  "ssa-return",
  "ssa-simple-phi",
  "ssa-simple",
  "ssa-single-if",
  "ssa-switch",
  "ssa-throw",
  // TODO: fix infinite loop
  // "ssa-while-no-reassign",
  "ssa-while",
  "type-field-load",
  "type-test-field-store",
  "type-test-primitive",
  "update-expression-constant-propagation",
]);

export default onlyFilter;
