/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// List derived from Firefox source code:
// https://github.com/mozilla-firefox/firefox/blob/58f365ba0eb5761a182f1925e4654cc75212b8ac/layout/style/test/property_database.js
export const shorthandToLonghand = {
  animation: [
    'animationDelay',
    'animationDirection',
    'animationDuration',
    'animationFillMode',
    'animationIterationCount',
    'animationName',
    'animationPlayState',
    'animationTimingFunction',
  ],
  background: [
    'backgroundAttachment',
    'backgroundClip',
    'backgroundColor',
    'backgroundImage',
    'backgroundOrigin',
    'backgroundPositionX',
    'backgroundPositionY',
    'backgroundRepeat',
    'backgroundSize',
  ],
  backgroundPosition: ['backgroundPositionX', 'backgroundPositionY'],
  border: [
    'borderBottomColor',
    'borderBottomStyle',
    'borderBottomWidth',
    'borderImageOutset',
    'borderImageRepeat',
    'borderImageSlice',
    'borderImageSource',
    'borderImageWidth',
    'borderLeftColor',
    'borderLeftStyle',
    'borderLeftWidth',
    'borderRightColor',
    'borderRightStyle',
    'borderRightWidth',
    'borderTopColor',
    'borderTopStyle',
    'borderTopWidth',
  ],
  borderBlock: [
    'borderBlockEndColor',
    'borderBlockEndStyle',
    'borderBlockEndWidth',
    'borderBlockStartColor',
    'borderBlockStartStyle',
    'borderBlockStartWidth',
  ],
  borderBlockColor: ['borderBlockEndColor', 'borderBlockStartColor'],
  borderBlockEnd: [
    'borderBlockEndColor',
    'borderBlockEndStyle',
    'borderBlockEndWidth',
  ],
  borderBlockStart: [
    'borderBlockStartColor',
    'borderBlockStartStyle',
    'borderBlockStartWidth',
  ],
  borderBlockStyle: ['borderBlockEndStyle', 'borderBlockStartStyle'],
  borderBlockWidth: ['borderBlockEndWidth', 'borderBlockStartWidth'],
  borderBottom: ['borderBottomColor', 'borderBottomStyle', 'borderBottomWidth'],
  borderColor: [
    'borderBottomColor',
    'borderLeftColor',
    'borderRightColor',
    'borderTopColor',
  ],
  borderImage: [
    'borderImageOutset',
    'borderImageRepeat',
    'borderImageSlice',
    'borderImageSource',
    'borderImageWidth',
  ],
  borderInline: [
    'borderInlineEndColor',
    'borderInlineEndStyle',
    'borderInlineEndWidth',
    'borderInlineStartColor',
    'borderInlineStartStyle',
    'borderInlineStartWidth',
  ],
  borderInlineColor: ['borderInlineEndColor', 'borderInlineStartColor'],
  borderInlineEnd: [
    'borderInlineEndColor',
    'borderInlineEndStyle',
    'borderInlineEndWidth',
  ],
  borderInlineStart: [
    'borderInlineStartColor',
    'borderInlineStartStyle',
    'borderInlineStartWidth',
  ],
  borderInlineStyle: ['borderInlineEndStyle', 'borderInlineStartStyle'],
  borderInlineWidth: ['borderInlineEndWidth', 'borderInlineStartWidth'],
  borderLeft: ['borderLeftColor', 'borderLeftStyle', 'borderLeftWidth'],
  borderRadius: [
    'borderBottomLeftRadius',
    'borderBottomRightRadius',
    'borderTopLeftRadius',
    'borderTopRightRadius',
  ],
  borderRight: ['borderRightColor', 'borderRightStyle', 'borderRightWidth'],
  borderStyle: [
    'borderBottomStyle',
    'borderLeftStyle',
    'borderRightStyle',
    'borderTopStyle',
  ],
  borderTop: ['borderTopColor', 'borderTopStyle', 'borderTopWidth'],
  borderWidth: [
    'borderBottomWidth',
    'borderLeftWidth',
    'borderRightWidth',
    'borderTopWidth',
  ],
  colorAdjust: ['printColorAdjust'],
  columnRule: ['columnRuleColor', 'columnRuleStyle', 'columnRuleWidth'],
  columns: ['columnCount', 'columnWidth'],
  containIntrinsicSize: ['containIntrinsicHeight', 'containIntrinsicWidth'],
  container: ['containerName', 'containerType'],
  flex: ['flexBasis', 'flexGrow', 'flexShrink'],
  flexFlow: ['flexDirection', 'flexWrap'],
  font: [
    'fontFamily',
    'fontFeatureSettings',
    'fontKerning',
    'fontLanguageOverride',
    'fontSize',
    'fontSizeAdjust',
    'fontStretch',
    'fontStyle',
    'fontVariant',
    'fontVariantAlternates',
    'fontVariantCaps',
    'fontVariantEastAsian',
    'fontVariantLigatures',
    'fontVariantNumeric',
    'fontVariantPosition',
    'fontWeight',
    'lineHeight',
  ],
  fontSynthesis: [
    'fontSynthesisPosition',
    'fontSynthesisSmallCaps',
    'fontSynthesisStyle',
    'fontSynthesisWeight',
  ],
  fontVariant: [
    'fontVariantAlternates',
    'fontVariantCaps',
    'fontVariantEastAsian',
    'fontVariantLigatures',
    'fontVariantNumeric',
    'fontVariantPosition',
  ],
  gap: ['columnGap', 'rowGap'],
  grid: [
    'gridAutoColumns',
    'gridAutoFlow',
    'gridAutoRows',
    'gridTemplateAreas',
    'gridTemplateColumns',
    'gridTemplateRows',
  ],
  gridArea: ['gridColumnEnd', 'gridColumnStart', 'gridRowEnd', 'gridRowStart'],
  gridColumn: ['gridColumnEnd', 'gridColumnStart'],
  gridColumnGap: ['columnGap'],
  gridGap: ['columnGap', 'rowGap'],
  gridRow: ['gridRowEnd', 'gridRowStart'],
  gridRowGap: ['rowGap'],
  gridTemplate: [
    'gridTemplateAreas',
    'gridTemplateColumns',
    'gridTemplateRows',
  ],
  inset: ['bottom', 'left', 'right', 'top'],
  insetBlock: ['insetBlockEnd', 'insetBlockStart'],
  insetInline: ['insetInlineEnd', 'insetInlineStart'],
  listStyle: ['listStyleImage', 'listStylePosition', 'listStyleType'],
  margin: ['marginBottom', 'marginLeft', 'marginRight', 'marginTop'],
  marginBlock: ['marginBlockEnd', 'marginBlockStart'],
  marginInline: ['marginInlineEnd', 'marginInlineStart'],
  marker: ['markerEnd', 'markerMid', 'markerStart'],
  mask: [
    'maskClip',
    'maskComposite',
    'maskImage',
    'maskMode',
    'maskOrigin',
    'maskPositionX',
    'maskPositionY',
    'maskRepeat',
    'maskSize',
  ],
  maskPosition: ['maskPositionX', 'maskPositionY'],
  offset: [
    'offsetAnchor',
    'offsetDistance',
    'offsetPath',
    'offsetPosition',
    'offsetRotate',
  ],
  outline: ['outlineColor', 'outlineStyle', 'outlineWidth'],
  overflow: ['overflowX', 'overflowY'],
  overscrollBehavior: ['overscrollBehaviorX', 'overscrollBehaviorY'],
  padding: ['paddingBottom', 'paddingLeft', 'paddingRight', 'paddingTop'],
  paddingBlock: ['paddingBlockEnd', 'paddingBlockStart'],
  paddingInline: ['paddingInlineEnd', 'paddingInlineStart'],
  pageBreakAfter: ['breakAfter'],
  pageBreakBefore: ['breakBefore'],
  pageBreakInside: ['breakInside'],
  placeContent: ['alignContent', 'justifyContent'],
  placeItems: ['alignItems', 'justifyItems'],
  placeSelf: ['alignSelf', 'justifySelf'],
  scrollMargin: [
    'scrollMarginBottom',
    'scrollMarginLeft',
    'scrollMarginRight',
    'scrollMarginTop',
  ],
  scrollMarginBlock: ['scrollMarginBlockEnd', 'scrollMarginBlockStart'],
  scrollMarginInline: ['scrollMarginInlineEnd', 'scrollMarginInlineStart'],
  scrollPadding: [
    'scrollPaddingBottom',
    'scrollPaddingLeft',
    'scrollPaddingRight',
    'scrollPaddingTop',
  ],
  scrollPaddingBlock: ['scrollPaddingBlockEnd', 'scrollPaddingBlockStart'],
  scrollPaddingInline: ['scrollPaddingInlineEnd', 'scrollPaddingInlineStart'],
  textDecoration: [
    'textDecorationColor',
    'textDecorationLine',
    'textDecorationStyle',
    'textDecorationThickness',
  ],
  textEmphasis: ['textEmphasisColor', 'textEmphasisStyle'],
  textWrap: ['textWrapMode', 'textWrapStyle'],
  transition: [
    'transitionBehavior',
    'transitionDelay',
    'transitionDuration',
    'transitionProperty',
    'transitionTimingFunction',
  ],
  verticalAlign: ['alignmentBaseline', 'baselineShift', 'baselineSource'],
  whiteSpace: ['textWrapMode', 'whiteSpaceCollapse'],
  wordWrap: ['overflowWrap'],
};
